version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: brian-blog-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brian_blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

